// Assignment Code

// 1. click button to generate a password
var generateBtn = document.querySelector("#generate");

// function to generate password
function generatePassword() {

    //select criteria for password 
   // created varaible which holds random characters/numbers generated by For Loop
  var getRandomUpper = [];
  for (var i = 0; i < 26; i++) {
    var x = String.fromCharCode(Math.floor(Math.random() * 26) + 65);
    getRandomUpper.push(x);
    
  }
  var getRandomLower = [];
  for (var i = 0; i < 26; i++) {
    var x = String.fromCharCode(Math.floor(Math.random() * 26) + 97);
    getRandomLower.push(x);
   
  }

  var getRandomNumber = [];
  for (var i = 0; i < 10; i++) {
    var x = String.fromCharCode(Math.floor(Math.random() * 10) + 48);
    getRandomNumber.push(x);
    
  }
  var specialChar = ["~", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+", "-", "=", "{", "}", "|", "[", "]", ";", "<", ">", "?", "/",];

  var getRandomSpecialChar = [];
  for (var i = 0; i < 25; i++) {
    var x = specialChar[Math.floor(Math.random() * specialChar.length)];
    getRandomSpecialChar.push(x);
  }

  //this variable will have all selected charater type + length stored
  var validUserInput = [];

  // this variable will have userInput prompt captrued 
  var userInput = prompt("Choose your password length");

  var parsed = parseInt(userInput);
 

  // prompt for length- at least 8 characters and no more than 128 characters
  if (Number.isNaN(parsed) || userInput < 8 || userInput > 128) {
    alert("Please enter valid length range between 8 and 128");
    return myPassword = "";
  }

  // -prompt for character types
  else {
    var confirmUpperCase = confirm(
      "Does your password includes upppercase letters ?"
    );
    if (confirmUpperCase) {
      validUserInput = validUserInput.concat(getRandomUpper);
    }
   

    var confirmLowerCase = confirm(
      "Does your password includes lowecase letters ?"
    );
    if (confirmLowerCase) {
      validUserInput = validUserInput.concat(getRandomLower);
    }
    

    var confirmNumbers = confirm(
      "Does your password includes numbers letters ?"
    );
    if (confirmNumbers) {
      validUserInput = validUserInput.concat(getRandomNumber);
    }
    

    var confirmSpecialChar = confirm(
      "Does your password includes special characters ?"
    );
    if (confirmSpecialChar) {
      validUserInput = validUserInput.concat(getRandomSpecialChar);
    }
   

    ///-check to make sure one character type is used
    if (
      !confirmUpperCase &&
      !confirmLowerCase &&
      !confirmNumbers &&
      !confirmSpecialChar
    ) {
      alert("Please choose atleast one character type");
      return myPassword = "";
    }
  }

  // variable that holds the generated password
  var myPassword = "";

  // for loop that chooses random characters in the arrays user chose
  for (var i = 0; i < userInput; i++) {
    var index = Math.floor(Math.random() * validUserInput.length);
    myPassword += validUserInput[index] + "";
  }
//B. generate password (using selected criteria!)
  // Returns user generated password
  return myPassword;
}

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;
}
////-alert or write it to the page
// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
